### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by markrtgh** [BSDStudios/ethr#1]
Nice. Hope this is the right place for a few suggestions.

**README.Rmd and README.md**

change `end_block=blocks[1]` to `end_block=blocks[2]`
remove line return and spaces between 50000, and parallel  

```
README.Rmd:Line120: BulkDownload <- bulkBlockDownload(start_block=blocks[1], end_block=blocks[1], data_dir, chunk_size = 50000,
                              parallel = TRUE, cores = 3)
```

change `reciept` to `receipt`
README.Rmd:Line 138: reciept <- eth_getTransactionReceipt(SingleTrans)
README.Rmd:Line 139: reciept
README.Rmd:Line 143: hexDec(reciept$gasUsed)

change `$blhash` to `$blHash`
README.Rmd:Line 153: blockHash <- transactions[49,]$blhash

**nodesPlot.Rd**
change `transaction` to `transactions`
nodesPlot.Rd:line 26: nodesPlot(transaction,degree_thres=50,save_plot=TRUE)

**Comment by tinmice** [comment]
Thanks! Will factor them in shortly.
