### ISSUE TITLE
package installs (probably correctly) but gives error

### ISSUE THREAD

**Issue by step21** [BSDStudios/ethr#3]
When installing, I got an error but i seemed to install fine. (`package(ethr)` worked without problem)
The output from installation was:
```
> devtools::install_github("BSDStudios/ethr")
Downloading GitHub repo BSDStudios/ethr@master
from URL https://api.github.com/repos/BSDStudios/ethr/zipball/master
Installing ethr
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/<User>/AppData/Local/Temp/Rtmp0qFgN7/devtools2bb024ee5c6a/BSDStudios-ethr-875ad25"  \
  --library="C:/Program Files/R/R-3.3.2/library" --install-tests 

The system cannot find the path specified.
* installing *source* package 'ethr' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (ethr)
Error: Command failed (1)
```
Is this anything to worry about or to be expected?

**Comment by ghost** [comment]
That's not something I've seen before, could be a local configuration issue. Let us know if there are any other problems. We need to update it to fix the Parity connection we faced last time around so I'll look into it in more detail then.

**Comment by ghost** [comment]
We had a couple of test modules which I removed last time around, it could be looking for those somewhere still.

>   "C:/Users/<User>/AppData/Local/Temp/Rtmp0qFgN7/devtools2bb024ee5c6a/BSDStudios-ethr-875ad25"  \
  --library="C:/Program Files/R/R-3.3.2/library" --install-tests

**Comment by step21** [comment]
Probably some weird windows issue, on Linux it's fine. Closing this. Are you in principle still working on this by the way?
