### ISSUE TITLE
NULL return

### ISSUE THREAD

**Issue by step21** [BSDStudios/ethr#4]
As I do not currently have a working local node, I tested with my test account of INFURA, which should have the same API as geth. I can set the rpc_adress correctly, but no matter which function I try, I always get 'NULL' as a return. This could be because of some incompatibility, but in case not, is there some way to debug?
F.e. when I tried eth_getBlockByNumber it requires also the argument 'full_list' but this is not in the json_rpc version, so what is it for/what to put there?
In a similar vein, do you plan to add more convenience functions in the future? As an example the JS api has things like getTransactionsByAccount or similar helpful things.
(sorry for mixing these things, I hope it is okay for now, some of it might be due to my R ignorance)

**Comment by ghost** [comment]
I had a similar issue when trying to use it with Parity (the NULL returns) - I've made some changes in the way that the JSON is constructed that forms the POST query and it is now working with Parity, so might be worth trying for your use. I've pushed it to the dev branch at the moment, I'm making more changes over the next week or so and there will be a new release at the end of that. Try the dev version for now though.

For the full list argument, have a look at the RPC documentation [here](https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_getblockbynumber) - in the parameters there is an option for expanding the return object and this is what the `full_list` option is replicating. I've made a couple of minor changes with how it handles this in the dev version as well.

No plans at the moment to add more convenience functions, but will make a note of it for when I do add some more.

**Comment by step21** [comment]
Thanks for the reply, sorry for only replying now. Are you still working on this, btw?

**Comment by ghost** [comment]
I'm still using it intermittently and I've got one more update to push at the moment, mainly just minor bug fixes though.

**Comment by step21** [comment]
That's fine, might be useful if I then do not  have to fix anything myself. See the new issue I opened for one example.
