### ISSUE TITLE
Error on GetBlockTransactions

### ISSUE THREAD

**Issue by step21** [BSDStudios/ethr#5]
```getBlockTransactions(start_block = 1, end_block = 2000)
  |                                                                           |   0%
Error in data.frame(blNumber = as.numeric(hexDec(block$number)), blTimestamp = as.POSIXct(as.numeric(hexDec(block$timestamp)),  : 
  arguments imply differing number of rows: 1, 0
```
When testing things, I got above error message. This is while connected to a local geth node, and other things such as `eth_blockNumber` work.

**Comment by ghost** [comment]
Fixed, there was a typo previously in the RPC interface which I had incorporated. It has since changed so I have updated. Fix will be in 0.9.13, currently on dev branch.
